<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Pytorch_NN_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy pandas torch scikit-learn

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import torch.nn as nn

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [8]:
#df.iloc[0]
#df.iloc[:] = df.head()
# all expect the target for x train and x test df.iloc[:,1:]
# only the target for y test and y train df.iloc[:,0]

In [9]:
df_test, df_train = train_test_split(df, test_size=0.2)

In [10]:
df_test.shape

(455, 31)

In [11]:
df_train.shape

(114, 31)

In [12]:
X_train = df_train.iloc[:,1:]
Y_train = df_train.iloc[:,0]

In [13]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
122,24.250,20.20,166.20,1761.0,0.14470,0.28670,0.42680,0.201200,0.2655,0.06877,...,26.020,23.99,180.90,2073.0,0.16960,0.4244,0.58030,0.22480,0.3222,0.08009
367,12.210,18.02,78.31,458.4,0.09231,0.07175,0.04392,0.020270,0.1695,0.05916,...,14.290,24.04,93.85,624.6,0.13680,0.2170,0.24130,0.08829,0.3218,0.07470
325,12.670,17.30,81.25,489.9,0.10280,0.07664,0.03193,0.021070,0.1707,0.05984,...,13.710,21.10,88.70,574.4,0.13840,0.1212,0.10200,0.05602,0.2688,0.06888
16,14.680,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.052590,0.1586,0.05922,...,19.070,30.88,123.40,1138.0,0.14640,0.1871,0.29140,0.16090,0.3029,0.08216
310,11.700,19.11,74.33,418.7,0.08814,0.05253,0.01583,0.011480,0.1936,0.06128,...,12.610,26.55,80.92,483.1,0.12230,0.1087,0.07915,0.05741,0.3487,0.06958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,13.170,18.22,84.28,537.3,0.07466,0.05994,0.04859,0.028700,0.1454,0.05549,...,14.900,23.89,95.10,687.6,0.12820,0.1965,0.18760,0.10450,0.2235,0.06925
287,12.890,13.12,81.89,515.9,0.06955,0.03729,0.02260,0.011710,0.1337,0.05581,...,13.620,15.54,87.40,577.0,0.09616,0.1147,0.11860,0.05366,0.2309,0.06915
461,27.420,26.27,186.90,2501.0,0.10840,0.19880,0.36350,0.168900,0.2061,0.05623,...,36.040,31.37,251.20,4254.0,0.13570,0.4256,0.68330,0.26250,0.2641,0.07427
412,9.397,21.68,59.75,268.8,0.07969,0.06053,0.03735,0.005128,0.1274,0.06724,...,9.965,27.99,66.61,301.0,0.10860,0.1887,0.18680,0.02564,0.2376,0.09206
144,10.750,14.97,68.26,355.3,0.07793,0.05139,0.02251,0.007875,0.1399,0.05688,...,11.950,20.72,77.79,441.2,0.10760,0.1223,0.09755,0.03413,0.2300,0.06769

In [14]:
Y_train

122    M
367    B
325    B
16     M
310    B
      ..
464    B
287    B
461    M
412    B
144    B
Name: diagnosis, Length: 114, dtype: object

In [15]:
X_test = df_test.iloc[:,1:]
Y_test = df_test.iloc[:,0]

In [16]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
394,12.10,17.72,78.07,446.2,0.10290,0.09758,0.04783,0.03326,0.1937,0.06161,...,13.56,25.80,88.33,559.5,0.14320,0.17730,0.16030,0.06266,0.3049,0.07081
263,15.61,19.38,100.00,758.6,0.07840,0.05616,0.04209,0.02847,0.1547,0.05443,...,17.91,31.67,115.90,988.6,0.10840,0.18070,0.22600,0.08568,0.2683,0.06829
74,12.31,16.52,79.19,470.9,0.09172,0.06829,0.03372,0.02272,0.1720,0.05914,...,14.11,23.21,89.71,611.1,0.11760,0.18430,0.17030,0.08660,0.2618,0.07609
340,14.42,16.54,94.15,641.2,0.09751,0.11390,0.08007,0.04223,0.1912,0.06412,...,16.67,21.51,111.40,862.1,0.12940,0.33710,0.37550,0.14140,0.3053,0.08764
119,17.95,20.01,114.20,982.0,0.08402,0.06722,0.07293,0.05596,0.2129,0.05025,...,20.58,27.83,129.20,1261.0,0.10720,0.12020,0.22490,0.11850,0.4882,0.06111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,11.74,14.69,76.31,426.0,0.08099,0.09661,0.06726,0.02639,0.1499,0.06758,...,12.45,17.60,81.25,473.8,0.10730,0.27930,0.26900,0.10560,0.2604,0.09879
37,13.03,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.02923,0.1467,0.05863,...,13.30,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169
109,11.34,21.26,72.48,396.5,0.08759,0.06575,0.05133,0.01899,0.1487,0.06529,...,13.01,29.15,83.99,518.1,0.16990,0.21960,0.31200,0.08278,0.2829,0.08832
328,16.27,20.71,106.90,813.7,0.11690,0.13190,0.14780,0.08488,0.1948,0.06277,...,19.28,30.38,129.80,1121.0,0.15900,0.29470,0.35970,0.15830,0.3103,0.08200
220,13.65,13.16,87.88,568.9,0.09646,0.08711,0.03888,0.02563,0.1360,0.06344,...,15.34,16.35,99.71,706.2,0.13110,0.24740,0.17590,0.08056,0.2380,0.08718

In [17]:
Y_test

394    B
263    M
74     B
340    B
119    M
      ..
510    B
37     B
109    B
328    M
220    B
Name: diagnosis, Length: 455, dtype: object

In [18]:
scale= StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [19]:
X_train

array([[ 2.69996178,  0.3362362 ,  2.88547783, ...,  1.66909639,
         0.39989614, -0.27351439],
       [-0.49352789, -0.2541787 , -0.51019916, ..., -0.4371634 ,
         0.39272847, -0.63102817],
       [-0.37151749, -0.44917811, -0.39661069, ..., -0.93506834,
        -0.55698752, -1.01706345],
       ...,
       [ 3.5407726 ,  1.9801896 ,  3.68523336, ...,  2.25078267,
        -0.64120762, -0.65954967],
       [-1.23964803,  0.73706833, -1.22727465, ..., -1.40381182,
        -1.11606562,  0.52044478],
       [-0.8807783 , -1.08021788, -0.89848626, ..., -1.27281669,
        -1.25225131, -1.09599507]])

In [20]:
X_test

array([[-0.59078158, -0.37287905, -0.58735776, ..., -0.78083458,
         0.27435725, -0.69830077],
       [ 0.42497596,  0.00166619,  0.33186358, ..., -0.43140783,
        -0.30668752, -0.83295185],
       [-0.53000976, -0.64363465, -0.54041166, ..., -0.41744291,
        -0.40987854, -0.4161747 ],
       ...,
       [-0.81071768,  0.42584995, -0.82166908, ..., -0.47542771,
        -0.07490464,  0.23731049],
       [ 0.6159731 ,  0.30175364,  0.62108507, ...,  0.67091059,
         0.36008517, -0.10038587],
       [-0.14222768, -1.40175031, -0.17616025, ..., -0.50912569,
        -0.78771639,  0.1763969 ]])

In [21]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.fit_transform(Y_test)

In [22]:
Y_train

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0])

In [23]:
Y_test

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

CONVERT NUMPY TO TENSOR TO USE GPU

In [24]:
X_train_tensor = torch.from_numpy(X_train)
Y_train_tensor = torch.from_numpy(Y_train)
X_test_tensor = torch.from_numpy(X_test)
Y_test_tensor = torch.from_numpy(Y_test)

In [25]:
X_train_tensor.shape

torch.Size([114, 30])

In [26]:
X_test_tensor.shape

torch.Size([455, 30])

In [27]:
Y_test_tensor.shape

torch.Size([455])

In [28]:
Y_train_tensor.shape

torch.Size([114])

DATA SET AND DATA LOADER

In [29]:
from torch.utils.data import Dataset, DataLoader

In [30]:
class Customdataset(Dataset):
  def __init__(self, X, y): # X IS FEAURES AND y is label
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [31]:
train_dataset = Customdataset(X_train_tensor, Y_train_tensor)
test_dataset = Customdataset(X_test_tensor, Y_train_tensor)

In [32]:
train_dataset[10]

(tensor([ 0.0980, -1.0233,  0.0948, -0.0438,  0.2228, -0.0032, -0.0539,  0.1882,
         -0.4299, -0.3155, -0.5296, -0.8238, -0.3546, -0.3684, -0.4859, -0.1257,
         -0.0563,  0.4944, -0.6885, -0.4785, -0.1000, -0.9979,  0.0189, -0.2164,
         -0.1617,  0.1523,  0.1523,  0.6677, -0.5516, -0.4897],
        dtype=torch.float64),
 tensor(0))

In [33]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

#DEFINING A MODEL

In [34]:
class MyNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad=True)

  def forward(self,X):
    z=  torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)

    loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [35]:
class MyNN2(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [36]:
loss_function = nn.BCELoss()

IMPORTATN PAPRAMS

In [37]:
learning_rate = 0.1
epochs = 25

TRAINING PARAMETER

In [38]:
# create model
model = MyNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, Y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.0262229090563504
Epoch: 2, Loss: 2.890891029269071
Epoch: 3, Loss: 2.7496776807922605
Epoch: 4, Loss: 2.6110859617092608
Epoch: 5, Loss: 2.4753548814954343
Epoch: 6, Loss: 2.3428041956044554
Epoch: 7, Loss: 2.206015434364539
Epoch: 8, Loss: 2.054635228832532
Epoch: 9, Loss: 1.9091087147808945
Epoch: 10, Loss: 1.77032492469842
Epoch: 11, Loss: 1.6392315358603182
Epoch: 12, Loss: 1.5106333671715393
Epoch: 13, Loss: 1.3826422858401817
Epoch: 14, Loss: 1.2666996459190762
Epoch: 15, Loss: 1.1639351025758193
Epoch: 16, Loss: 1.0752359394076079
Epoch: 17, Loss: 1.001065551435046
Epoch: 18, Loss: 0.9411637259099483
Epoch: 19, Loss: 0.8941614122421031
Epoch: 20, Loss: 0.8576864801970985
Epoch: 21, Loss: 0.8291870192385191
Epoch: 22, Loss: 0.8065905990548534
Epoch: 23, Loss: 0.7883977925355572
Epoch: 24, Loss: 0.7735441729358923
Epoch: 25, Loss: 0.7612646898762215

In [41]:
X_train_tensor_for_nnmodule = X_train_tensor.float()
Y_train_tensor_for_nnmodule = Y_train_tensor.float()

AttributeError: 'DataLoader' object has no attribute 'float'

In [42]:
# create model
model2 = MyNN2(X_train_tensor_for_nnmodule.shape[1])

#optimizer
optimizer = torch.optim.SGD(model2.parameters(), lr=learning_rate)

#loss function
loss_function = nn.BCELoss()

In [43]:
# define loop
for epoch in range(epochs):
  for batch_feaures, batch_labels in train_loader:
    # forward pass
    y_pred = model2.forward(batch_feaures)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()


  print(f'Epoch: {epoch+1}, Loss:{loss.item()}')

RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

In [ ]:
Y_train_tensor_for_nnmodule

In [ ]:
Y_train_tensor_for_nnmodule.reshape(-1,1)

In [ ]:
model.bias

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

In [ ]:
X_test_tensor_for_nnmodule = X_test_tensor.float()
Y_test_tensor_for_nnmodule = Y_test_tensor.float()

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model2.forward(X_test_tensor_for_nnmodule)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor_for_nnmodule).float().mean()
  print(f'Accuracy: {accuracy.item()}')

In [ ]:
model2.linear.bias

In [ ]:
model2.linear.weight

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model2, input_size=(455, 30))

In [ ]:
from torchinfo import summary
summary(model2, input_size=(455, 30))