<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Pytorch_NN_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
pip install numpy pandas torch scikit-learn

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [60]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import torch.nn as nn

In [61]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [62]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [63]:
df.shape

(569, 33)

In [64]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [65]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [66]:
#df.iloc[0]
#df.iloc[:] = df.head()
# all expect the target for x train and x test df.iloc[:,1:]
# only the target for y test and y train df.iloc[:,0]

In [67]:
df_test, df_train = train_test_split(df, test_size=0.2)

In [68]:
df_test.shape

(455, 31)

In [69]:
df_train.shape

(114, 31)

In [70]:
X_train = df_train.iloc[:,1:]
Y_train = df_train.iloc[:,0]

In [71]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
488,11.68,16.17,75.49,420.5,0.11280,0.09263,0.042790,0.031320,0.1853,0.06401,...,13.32,21.59,86.57,549.8,0.15260,0.14770,0.149000,0.09815,0.2804,0.08024
37,13.03,18.42,82.61,523.8,0.08983,0.03766,0.025620,0.029230,0.1467,0.05863,...,13.30,22.81,84.46,545.9,0.09701,0.04619,0.048330,0.05013,0.1987,0.06169
89,14.64,15.24,95.77,651.9,0.11320,0.13390,0.099660,0.070640,0.2116,0.06346,...,16.34,18.24,109.40,803.6,0.12770,0.30890,0.260400,0.13970,0.3151,0.08473
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.144000,0.097910,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.321500,0.16280,0.2572,0.06637
506,12.22,20.04,79.47,453.1,0.10960,0.11520,0.081750,0.021660,0.2124,0.06894,...,13.16,24.17,85.13,515.3,0.14020,0.23150,0.353500,0.08088,0.2709,0.08839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,15.37,22.76,100.20,728.2,0.09200,0.10360,0.112200,0.074830,0.1717,0.06097,...,16.43,25.84,107.50,830.9,0.12570,0.19970,0.284600,0.14760,0.2556,0.06828
333,11.25,14.78,71.38,390.0,0.08306,0.04458,0.000974,0.002941,0.1773,0.06081,...,12.76,22.06,82.08,492.7,0.11660,0.09794,0.005518,0.01667,0.2815,0.07418
419,11.16,21.41,70.95,380.3,0.10180,0.05978,0.008955,0.010760,0.1615,0.06144,...,12.36,28.92,79.26,458.0,0.12820,0.11080,0.035820,0.04306,0.2976,0.07123
544,13.87,20.70,89.77,584.8,0.09578,0.10180,0.036880,0.023690,0.1620,0.06688,...,15.05,24.75,99.17,688.6,0.12640,0.20370,0.137700,0.06845,0.2249,0.08492
315,12.49,16.85,79.19,481.6,0.08511,0.03834,0.004473,0.006423,0.1215,0.05673,...,13.34,19.71,84.48,544.2,0.11040,0.04953,0.019380,0.02784,0.1917,0.06174

In [72]:
Y_train

488    B
37     B
89     B
565    M
506    B
      ..
91     M
333    B
419    B
544    B
315    B
Name: diagnosis, Length: 114, dtype: object

In [73]:
X_test = df_test.iloc[:,1:]
Y_test = df_test.iloc[:,0]

In [74]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
260,20.31,27.06,132.90,1288.0,0.10000,0.10880,0.151900,0.093330,0.1814,0.05572,...,24.33,39.16,162.30,1844.0,0.15220,0.29450,0.378800,0.16970,0.3151,0.07999
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.241400,0.105200,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.686900,0.25750,0.6638,0.17300
319,12.43,17.00,78.60,477.3,0.07557,0.03454,0.013420,0.016990,0.1472,0.05561,...,12.90,20.21,81.76,515.9,0.08409,0.04712,0.022370,0.02832,0.1901,0.05932
478,11.49,14.59,73.99,404.9,0.10460,0.08228,0.053080,0.019690,0.1779,0.06574,...,12.40,21.90,82.04,467.6,0.13520,0.20100,0.259600,0.07431,0.2941,0.09180
93,13.45,18.30,86.60,555.1,0.10220,0.08165,0.039740,0.027800,0.1638,0.05710,...,15.10,25.94,97.59,699.4,0.13390,0.17510,0.138100,0.07911,0.2678,0.06603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,18.22,18.70,120.30,1033.0,0.11480,0.14850,0.177200,0.106000,0.2092,0.06310,...,20.60,24.13,135.10,1321.0,0.12800,0.22970,0.262300,0.13250,0.3021,0.07987
5,12.45,15.70,82.57,477.1,0.12780,0.17000,0.157800,0.080890,0.2087,0.07613,...,15.47,23.75,103.40,741.6,0.17910,0.52490,0.535500,0.17410,0.3985,0.12440
346,12.06,18.90,76.66,445.3,0.08386,0.05794,0.007510,0.008488,0.1555,0.06048,...,13.64,27.06,86.54,562.6,0.12890,0.13520,0.045060,0.05093,0.2880,0.08083
327,12.03,17.93,76.09,446.0,0.07683,0.03892,0.001546,0.005592,0.1382,0.06070,...,13.07,22.25,82.74,523.4,0.10130,0.07390,0.007732,0.02796,0.2171,0.07037
106,11.64,18.33,75.17,412.5,0.11420,0.10170,0.070700,0.034850,0.1801,0.06520,...,13.14,29.26,85.51,521.7,0.16880,0.26600,0.287300,0.12180,0.2806,0.09097

In [75]:
Y_test

260    M
3      M
319    B
478    B
93     B
      ..
53     M
5      M
346    B
327    B
106    B
Name: diagnosis, Length: 455, dtype: object

In [76]:
scale= StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [77]:
X_train

array([[-7.08879414e-01, -8.22314157e-01, -6.99324269e-01, ...,
        -3.15420787e-01, -8.01815039e-02, -2.78973138e-01],
       [-3.44951329e-01, -3.14492847e-01, -4.21259497e-01, ...,
        -1.07861735e+00, -1.50373181e+00, -1.43822740e+00],
       [ 8.90666104e-02, -1.03221363e+00,  9.26916832e-02, ...,
         3.44946089e-01,  5.24435334e-01,  1.62263802e-03],
       ...,
       [-8.49059121e-01,  3.60345250e-01, -8.76629615e-01, ...,
        -1.19098303e+00,  2.19513298e-01, -8.42039495e-01],
       [-1.18507186e-01,  2.00099415e-01, -1.41632563e-01, ...,
        -7.87451983e-01, -1.04721996e+00,  1.34964014e-02],
       [-4.90522563e-01, -6.68839272e-01, -5.54824317e-01, ...,
        -1.43287915e+00, -1.62570063e+00, -1.43510273e+00]])

In [78]:
X_test

array([[ 1.79461402,  1.85785194,  1.72611179, ...,  0.84353627,
         0.37818742, -0.20336923],
       [-0.76690297,  0.28722339, -0.58659481, ...,  2.16742536,
         5.93002999,  4.81950518],
       [-0.47588698, -0.50749585, -0.54395272, ..., -1.28825689,
        -1.61200564, -1.31962355],
       ...,
       [-0.5824968 , -0.06076018, -0.62505631, ..., -0.94733283,
        -0.05328644, -0.15800621],
       [-0.59114083, -0.2888305 , -0.64888572, ..., -1.29368514,
        -1.18212394, -0.72288382],
       [-0.70351335, -0.19478088, -0.68734722, ...,  0.12127787,
        -0.17110586,  0.38959025]])

In [79]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.fit_transform(Y_test)

In [80]:
Y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0])

In [81]:
Y_test

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0])

CONVERT NUMPY TO TENSOR TO USE GPU

In [82]:
X_train_tensor = torch.from_numpy(X_train).float()
Y_train_tensor = torch.from_numpy(Y_train).float()
X_test_tensor  = torch.from_numpy(X_test).float()
Y_test_tensor  = torch.from_numpy(Y_test).float()

In [83]:
X_train_tensor.shape

torch.Size([114, 30])

In [84]:
X_test_tensor.shape

torch.Size([455, 30])

In [85]:
Y_test_tensor.shape

torch.Size([455])

In [86]:
Y_train_tensor.shape

torch.Size([114])

DATA SET AND DATA LOADER

In [87]:
from torch.utils.data import Dataset, DataLoader

In [88]:
class Customdataset(Dataset):
  def __init__(self, X, y): # X IS FEAURES AND y is label
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [89]:
train_dataset = Customdataset(X_train_tensor, Y_train_tensor)
test_dataset = Customdataset(X_test_tensor, Y_test_tensor)

In [90]:
train_dataset[10]

(tensor([ 0.0271, -0.0188,  0.1028, -0.0642, -0.6551,  1.0026,  0.5146,  0.3626,
         -0.3148,  1.1439,  1.4503,  0.6833,  0.5864,  0.5571,  0.1978,  3.6481,
          2.6303,  2.2040,  2.3938,  6.5957, -0.1373, -0.6726, -0.2061, -0.2273,
         -1.4557, -0.1068, -0.2592, -0.2526, -1.0071,  0.2054]),
 tensor(0.))

In [91]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

#DEFINING A MODEL

In [92]:
class MyNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float32, requires_grad=True)
    self.bias = torch.zeros(1, dtype= torch.float32, requires_grad=True)

  def forward(self,X):
    z=  torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)

    loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [93]:
class MyNN2(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [94]:
loss_function = nn.BCELoss()

IMPORTATN PAPRAMS

In [95]:
learning_rate = 0.1
epochs = 25

TRAINING PARAMETER

In [96]:
# create model
model = MyNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, Y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.3406875133514404
Epoch: 2, Loss: 3.2169880867004395
Epoch: 3, Loss: 3.094393253326416
Epoch: 4, Loss: 2.9716835021972656
Epoch: 5, Loss: 2.843132257461548
Epoch: 6, Loss: 2.716017723083496
Epoch: 7, Loss: 2.5821845531463623
Epoch: 8, Loss: 2.4392857551574707
Epoch: 9, Loss: 2.3005940914154053
Epoch: 10, Loss: 2.1508944034576416
Epoch: 11, Loss: 2.0058040618896484
Epoch: 12, Loss: 1.8663583993911743
Epoch: 13, Loss: 1.7011184692382812
Epoch: 14, Loss: 1.5447615385055542
Epoch: 15, Loss: 1.4010426998138428
Epoch: 16, Loss: 1.270911455154419
Epoch: 17, Loss: 1.155860424041748
Epoch: 18, Loss: 1.056779146194458
Epoch: 19, Loss: 0.973907470703125
Epoch: 20, Loss: 0.906795084476471
Epoch: 21, Loss: 0.8543144464492798
Epoch: 22, Loss: 0.8147422671318054
Epoch: 23, Loss: 0.7859120965003967
Epoch: 24, Loss: 0.7654580473899841
Epoch: 25, Loss: 0.7511117458343506

In [97]:
# create model
model2 = MyNN2(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD(model2.parameters(), lr=learning_rate)

#loss function
loss_function = nn.BCELoss()

In [98]:
# define loop
for epoch in range(epochs):
  for batch_feaures, batch_labels in train_loader:
    # forward pass
    y_pred = model2.forward(batch_feaures)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()


  print(f'Epoch: {epoch+1}, Loss:{loss.item()}')

Epoch: 1, Loss:0.44944271445274353
Epoch: 2, Loss:0.3734188675880432
Epoch: 3, Loss:0.2104351967573166
Epoch: 4, Loss:0.30122146010398865
Epoch: 5, Loss:0.2009890079498291
Epoch: 6, Loss:0.1629924327135086
Epoch: 7, Loss:0.19673633575439453
Epoch: 8, Loss:0.09670974314212799
Epoch: 9, Loss:0.14637422561645508
Epoch: 10, Loss:0.14374509453773499
Epoch: 11, Loss:0.1520971804857254
Epoch: 12, Loss:0.08062884211540222
Epoch: 13, Loss:0.13021288812160492
Epoch: 14, Loss:0.21631544828414917
Epoch: 15, Loss:0.13140609860420227
Epoch: 16, Loss:0.2326696515083313
Epoch: 17, Loss:0.16076694428920746
Epoch: 18, Loss:0.12738434970378876
Epoch: 19, Loss:0.09708110988140106
Epoch: 20, Loss:0.13500554859638214
Epoch: 21, Loss:0.10053615272045135
Epoch: 22, Loss:0.12364644557237625
Epoch: 23, Loss:0.22150668501853943
Epoch: 24, Loss:0.09572897851467133
Epoch: 25, Loss:0.1743629276752472

In [99]:
model.bias

tensor([-0.1384], requires_grad=True)

In [100]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6274411082267761

In [101]:
# model 2 evaluation with test loader

model2.eval() # set moodel to evaluation mode
accuracy_list =[]

with torch.no_grad():
  for batch_feaures, batch_labels in test_loader:
    y_pred = model2.forward(batch_feaures) # forward pass
    y_pred = (y_pred > 0.8).float() #convert probabalitlies to biary classification


    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item() #calcualte accuracy for the current batch
    accuracy_list.append(batch_accuracy)

#calcualte overall accuracy
  overall_accuracy = sum(accuracy_list) / len(accuracy_list)
  print(f'Accuracy: {overall_accuracy:4f}')

Accuracy: 0.954167

In [102]:
model2.linear.bias

Parameter containing:
tensor([-0.3735], requires_grad=True)

In [103]:
model2.linear.weight

Parameter containing:
tensor([[ 0.3368,  0.4531,  0.3450,  0.2452,  0.0508,  0.1585,  0.1884,  0.4024,
          0.1918, -0.3058,  0.0435,  0.0061,  0.1469,  0.3227, -0.0146, -0.0719,
         -0.0199,  0.0743, -0.1220, -0.2356,  0.3614,  0.5298,  0.4741,  0.4601,
          0.4618,  0.2164,  0.4619,  0.4202,  0.4112, -0.0042]],
       requires_grad=True)

In [104]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [105]:
from torchinfo import summary
summary(model2, input_size=(455, 30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MyNN2                                    [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================

In [106]:
from torchinfo import summary
summary(model2, input_size=(455, 30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MyNN2                                    [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================