<a href="https://colab.research.google.com/github/Zaki2409/AI-Engineer-Hands-on/blob/master/Pytorch_NN_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy pandas torch scikit-learn

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.11.0+cu128)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import torch.nn as nn

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
#df.iloc[0]
#df.iloc[:] = df.head()
# all expect the target for x train and x test df.iloc[:,1:]
# only the target for y test and y train df.iloc[:,0]

In [8]:
df_test, df_train = train_test_split(df, test_size=0.2)

In [9]:
df_test.shape

(455, 31)

In [10]:
df_train.shape

(114, 31)

In [11]:
X_train = df_train.iloc[:,1:]
Y_train = df_train.iloc[:,0]

In [12]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
282,19.400,18.18,127.20,1145.0,0.10370,0.14420,0.16260,0.094640,0.1893,0.05892,...,23.790,28.65,152.40,1628.0,0.1518,0.37490,0.43160,0.22520,0.3590,0.07787
467,9.668,18.10,61.06,286.3,0.08311,0.05428,0.01479,0.005769,0.1680,0.06412,...,11.150,24.62,71.11,380.2,0.1388,0.12550,0.06409,0.02500,0.3057,0.07875
5,12.450,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.080890,0.2087,0.07613,...,15.470,23.75,103.40,741.6,0.1791,0.52490,0.53550,0.17410,0.3985,0.12440
61,8.598,20.98,54.66,221.8,0.12430,0.08963,0.03000,0.009259,0.1828,0.06757,...,9.565,27.04,62.06,273.9,0.1639,0.16980,0.09001,0.02778,0.2972,0.07712
98,11.600,12.84,74.34,412.6,0.08983,0.07525,0.04196,0.033500,0.1620,0.06582,...,13.060,17.16,82.96,512.5,0.1431,0.18510,0.19220,0.08449,0.2772,0.08756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,11.900,14.65,78.11,432.8,0.11520,0.12960,0.03710,0.030030,0.1995,0.07839,...,13.150,16.51,86.26,509.6,0.1424,0.25170,0.09420,0.06042,0.2727,0.10360
318,9.042,18.90,60.07,244.5,0.09968,0.19720,0.19750,0.049080,0.2330,0.08743,...,10.060,23.40,68.62,297.1,0.1221,0.37480,0.46090,0.11450,0.3135,0.10550
238,14.220,27.85,92.55,623.9,0.08223,0.10390,0.11030,0.044080,0.1342,0.06129,...,15.750,40.54,102.50,764.0,0.1081,0.24260,0.30640,0.08219,0.1890,0.07796
50,11.760,21.60,74.72,427.9,0.08637,0.04966,0.01657,0.011150,0.1495,0.05888,...,12.980,25.72,82.98,516.5,0.1085,0.08615,0.05523,0.03715,0.2433,0.06563
85,18.460,18.52,121.10,1075.0,0.09874,0.10530,0.13350,0.087950,0.2132,0.06022,...,22.930,27.68,152.20,1603.0,0.1398,0.20890,0.31570,0.16420,0.3695,0.08579

In [13]:
Y_train

282    M
467    B
5      M
61     B
98     B
      ..
145    B
318    B
238    B
50     B
85     M
Name: diagnosis, Length: 114, dtype: object

In [14]:
X_test = df_test.iloc[:,1:]
Y_test = df_test.iloc[:,0]

In [15]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
505,9.676,13.14,64.12,272.5,0.12550,0.22040,0.11880,0.07038,0.2057,0.09575,...,10.60,18.04,69.47,328.1,0.2006,0.3663,0.29130,0.10750,0.2848,0.13640
295,13.770,13.27,88.06,582.7,0.09198,0.06221,0.01063,0.01917,0.1592,0.05912,...,14.67,16.93,94.17,661.1,0.1170,0.1072,0.03732,0.05802,0.2823,0.06794
183,11.410,14.92,73.53,402.0,0.09059,0.08155,0.06181,0.02361,0.1167,0.06217,...,12.37,17.70,79.12,467.2,0.1121,0.1610,0.16480,0.06296,0.1811,0.07427
173,11.080,14.71,70.21,372.7,0.10060,0.05743,0.02363,0.02583,0.1566,0.06669,...,11.35,16.82,72.01,396.5,0.1216,0.0824,0.03938,0.04306,0.1902,0.07313
527,12.340,12.27,78.94,468.5,0.09003,0.06307,0.02958,0.02647,0.1689,0.05808,...,13.61,19.27,87.22,564.9,0.1292,0.2074,0.17910,0.10700,0.3110,0.07592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,16.350,23.29,109.00,840.4,0.09742,0.14970,0.18110,0.08773,0.2175,0.06218,...,19.38,31.03,129.30,1165.0,0.1415,0.4665,0.70870,0.22480,0.4824,0.09614
503,23.090,19.83,152.10,1682.0,0.09342,0.12750,0.16760,0.10030,0.1505,0.05484,...,30.79,23.87,211.50,2782.0,0.1199,0.3625,0.37940,0.22640,0.2908,0.07277
376,10.570,20.22,70.15,338.3,0.09073,0.16600,0.22800,0.05941,0.2188,0.08450,...,10.85,22.82,76.51,351.9,0.1143,0.3619,0.60300,0.14650,0.2597,0.12000
225,14.340,13.47,92.51,641.2,0.09906,0.07624,0.05724,0.04603,0.2075,0.05448,...,16.77,16.90,110.40,873.2,0.1297,0.1525,0.16320,0.10870,0.3062,0.06072
336,12.990,14.23,84.08,514.3,0.09462,0.09965,0.03738,0.02098,0.1652,0.07238,...,13.72,16.91,87.38,576.0,0.1142,0.1975,0.14500,0.05850,0.2432,0.10090

In [16]:
Y_test

505    B
295    B
183    B
173    B
527    B
      ..
370    M
503    M
376    B
225    B
336    B
Name: diagnosis, Length: 455, dtype: object

In [17]:
scale= StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [18]:
X_train

array([[ 1.63236657, -0.24082355,  1.62292693, ...,  1.81731813,
         1.20466404, -0.28866394],
       [-1.253551  , -0.2585386 , -1.28127676, ..., -1.40918301,
         0.26937237, -0.24196981],
       [-0.4285795 , -0.78998983, -0.33677386, ...,  0.99377064,
         1.89779764,  2.18028829],
       ...,
       [ 0.09629454,  1.90048206,  0.10144738, ..., -0.48748671,
        -1.77844259, -0.28388841],
       [-0.63319141,  0.51649446, -0.68146692, ..., -1.21336888,
        -0.82560324, -0.93813687],
       [ 1.35361991, -0.16553463,  1.35507628, ...,  0.83421838,
         1.38891475,  0.13158324]])

In [19]:
X_test

array([[-1.26852183, -1.45146232, -1.14870836, ..., -0.11495915,
        -0.08269856,  2.93205186],
       [-0.11686074, -1.42080686, -0.17636703, ..., -0.85856066,
        -0.12240378, -0.90633739],
       [-0.78073963, -1.03171829, -0.76651404, ..., -0.78432074,
        -1.72967116, -0.55142935],
       ...,
       [-1.0170355 ,  0.21808136, -0.90379531, ...,  0.47114551,
        -0.48133899,  2.0125429 ],
       [ 0.04348289, -1.37364461,  0.00437311, ..., -0.09692516,
         0.25717814, -1.3111456 ],
       [-0.33627834, -1.19442806, -0.33801776, ..., -0.85134707,
        -0.74339345,  0.94165136]])

In [20]:
encoder = LabelEncoder()
Y_train = encoder.fit_transform(Y_train)
Y_test = encoder.fit_transform(Y_test)

In [21]:
Y_train

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1])

In [22]:
Y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0])

CONVERT NUMPY TO TENSOR TO USE GPU

In [23]:
X_train_tensor = torch.from_numpy(X_train)
Y_train_tensor = torch.from_numpy(Y_train)
X_test_tensor = torch.from_numpy(X_test)
Y_test_tensor = torch.from_numpy(Y_test)

In [24]:
X_train_tensor.shape

torch.Size([114, 30])

In [25]:
X_test_tensor.shape

torch.Size([455, 30])

In [26]:
Y_test_tensor.shape

torch.Size([455])

In [27]:
Y_train_tensor.shape

torch.Size([114])

#DEFINING A MODEL

In [28]:
class MyNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1], 1, dtype= torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad=True)

  def forward(self,X):
    z=  torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)

    loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [29]:
class MyNN2(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [30]:
loss_function = nn.BCELoss()

IMPORTATN PAPRAMS

In [31]:
learning_rate = 0.1
epochs = 25

TRAINING PARAMETER

In [32]:
# create model
model = MyNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, Y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.395579174398783
Epoch: 2, Loss: 3.288787509122307
Epoch: 3, Loss: 3.1722268934239493
Epoch: 4, Loss: 3.0516415707671545
Epoch: 5, Loss: 2.9326659098484296
Epoch: 6, Loss: 2.802134716064219
Epoch: 7, Loss: 2.665930863839886
Epoch: 8, Loss: 2.523497197825836
Epoch: 9, Loss: 2.373397768405383
Epoch: 10, Loss: 2.2197065521559916
Epoch: 11, Loss: 2.0707129776826276
Epoch: 12, Loss: 1.9227474509744458
Epoch: 13, Loss: 1.7720057121438753
Epoch: 14, Loss: 1.6292562294598967
Epoch: 15, Loss: 1.4958814461939813
Epoch: 16, Loss: 1.3733163170313518
Epoch: 17, Loss: 1.2629074964089093
Epoch: 18, Loss: 1.16572952862859
Epoch: 19, Loss: 1.0823651732582513
Epoch: 20, Loss: 1.0127014936518188
Epoch: 21, Loss: 0.9558550135257226
Epoch: 22, Loss: 0.9103146856590515
Epoch: 23, Loss: 0.8742512977103742
Epoch: 24, Loss: 0.8458315737270008
Epoch: 25, Loss: 0.8234117487820708

In [33]:
X_train_tensor_for_nnmodule = X_train_tensor.float()
Y_train_tensor_for_nnmodule = Y_train_tensor.float()

In [34]:
# create model
model2 = MyNN2(X_train_tensor_for_nnmodule.shape[1])

#optimizer
optimizer = torch.optim.SGD(model2.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model2(X_train_tensor_for_nnmodule)

  # loss calculate
  loss = loss_function(y_pred, Y_train_tensor_for_nnmodule.reshape(-1,1))


  # zero gradients -> clearing gradeint beofre backward pass is a good stratrgy
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # zero gradients
  optimizer.zero_grad()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6891062259674072
Epoch: 2, Loss: 0.5484299659729004
Epoch: 3, Loss: 0.46743249893188477
Epoch: 4, Loss: 0.4143379330635071
Epoch: 5, Loss: 0.3760656416416168
Epoch: 6, Loss: 0.34673115611076355
Epoch: 7, Loss: 0.32329973578453064
Epoch: 8, Loss: 0.3040263056755066
Epoch: 9, Loss: 0.2878221869468689
Epoch: 10, Loss: 0.27396517992019653
Epoch: 11, Loss: 0.2619529366493225
Epoch: 12, Loss: 0.2514224052429199
Epoch: 13, Loss: 0.24210324883460999
Epoch: 14, Loss: 0.23378890752792358
Epoch: 15, Loss: 0.2263186126947403
Epoch: 16, Loss: 0.21956472098827362
Epoch: 17, Loss: 0.2134246826171875
Epoch: 18, Loss: 0.20781484246253967
Epoch: 19, Loss: 0.2026662677526474
Epoch: 20, Loss: 0.1979217827320099
Epoch: 21, Loss: 0.19353321194648743
Epoch: 22, Loss: 0.18945996463298798
Epoch: 23, Loss: 0.18566744029521942
Epoch: 24, Loss: 0.1821260005235672
Epoch: 25, Loss: 0.1788100302219391

In [35]:
Y_train_tensor_for_nnmodule

tensor([1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
        0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 0., 1.])

In [36]:
Y_train_tensor_for_nnmodule.reshape(-1,1)

tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]])

In [37]:
model.bias

tensor([-0.1565], dtype=torch.float64, requires_grad=True)

In [38]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6223548054695129

In [40]:
X_test_tensor_for_nnmodule = X_test_tensor.float()
Y_test_tensor_for_nnmodule = Y_test_tensor.float()

In [42]:
# model evaluation
with torch.no_grad():
  y_pred = model2.forward(X_test_tensor_for_nnmodule)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == Y_test_tensor_for_nnmodule).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5647096037864685

In [43]:
model2.linear.bias

Parameter containing:
tensor([-0.0844], requires_grad=True)

In [44]:
model2.linear.weight

Parameter containing:
tensor([[ 0.2023,  0.2349,  0.3349,  0.1238, -0.0611,  0.1778,  0.2022,  0.1066,
          0.1927,  0.0654,  0.0328, -0.1976,  0.0602,  0.1294,  0.0380,  0.0011,
          0.0655, -0.1455, -0.0454, -0.1787,  0.4433,  0.1779,  0.3484,  0.3369,
          0.0546,  0.2530,  0.2649,  0.3968,  0.1045,  0.0238]],
       requires_grad=True)

In [45]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [46]:
from torchinfo import summary
summary(model2, input_size=(455, 30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MyNN2                                    [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================

In [47]:
from torchinfo import summary
summary(model2, input_size=(455, 30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MyNN2                                    [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================